export const helpData = [
    {
        name: 'Logout',
        description: "To log out of the system, click on the logout button at the top left of the tabs."
    },
    {
        name: 'Workshop',
        description: "Click on the buttons under the workshop tab to navigate to the specific workshop item you would like to view or edit."
    },
    {
        name: 'Products',
        description: "Search, add, delete or edit products under the products tab. Click the delete icon to delete, the edit icon to edit and the add button to add a product."
    },
    {
        name: 'Clients',
        description: "View and manage your clients under the client tab."
    },
    {
        name: 'Deliveries',
        description: "The delivery page consists of information about the different delivery companies that can be used. To add a delviery company, click on the Add Delivery Company Button and you will be redirected to a page where you can enter the delivery company details and save them. To update a delivery compnay's details, click on the pencil icon in the row of the delivery company you want to edit. You will then be redirected to a page where you can update the details of selected delivery company. To Delete a delivery company, click on the trashbin icon in the row of the delivery company you would like to delete."
    },
    {
        name: 'Discounts',
        description: "The Discounts page consists of information on the different discounts that can be made and applied system wide. To add To add a discount, click on the Add Discount  Button and you will be redirected to a page where you can enter the discount details and save them. To update a discount's details, click on the pencil icon in the row of the discount  you want to edit. You will then be redirected to a page where you can update the details of selected discount. To Delete a discount, click on the trashbin icon in the row of the discount you would like to delete."
    },
    {
        name: 'Inventory',
        description: "The inventory page consists  of the information and activities you can perform with regards to the inventory. As the administrator, you can view the inventory list. You can also add an inventory item. As the administrator, you can edit inventory item details by clicking on the pencil icon and entering the update details after being redirected. You can also delete an inventory item by clicking on the trashbin icon in the row of the inventory item you want to delete. You can perform other tasks with inventory such as performing a stock take, writing off an inventory item and a write off reason."
    },
    {
        name: 'Newsletter',
        description: "The newsletter is sent out to users that have subscribed. As the administrator, you can generate a news letter by uploading the pdf of the newsletter and sending it by clicking the send newsletter button. The newsletter will send to all clients that subscribed."
    }, 
    {
        name: 'Orders',
        description: "The orders page consists of information on all the orders that clients have placed."
    },
    {
        name: 'Policy',
        description: "The Policy page consists of policies that are added by the administrator. These policies can be business rules that will be displayed to the clients"
    },
    {
        name: 'Reports',
        description: "The Reports page consists of many different reports that can be generated by the administrator to help them make business decision. There are five reports, namely Inventory report, Order Report, Workshop Performance, Product Performance, Client Report and Supplier Purchase Report. To generate any of the reports, click on the button with the buttons name on it. You will then be redirected to the reports own page. There are reports that require details, fill in the details and click on the Generate button. Reports can also be downloaded into pdf files by simply clicking on the Download Pdf button."
    },
    {
        name: 'Suppliers',
        description: "The Supplier page consists of information on the different supplier that can be purchased from. To add To add a supplier, click on the Add Supplier  Button and you will be redirected to a page where you can enter the supplier details and save them. To update a supplier's details, click on the pencil icon in the row of the supplier you want to edit. You will then be redirected to a page where you can update the details of selected supplier. To Delete a supplier, click on the trashbin icon in the row of the supplier you would like to delete."
    },
]